-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

vim.keymap.set("n", "\\1", ":!")
vim.keymap.set("n", "\\b", "orequire 'pry'; binding.pry<ESC>")
vim.keymap.set("n", "\\B", "Orequire 'pry'; binding.pry<ESC>")
vim.keymap.set("n", "\\bd", ":bp<cr>:bd #<cr>")
vim.keymap.set("n", "\\cl", "oconsole.log()<ESC>i")
vim.keymap.set("n", "\\Cl", "Oconsole.log()<ESC>i")
vim.keymap.set("n", "\\cp", ":!cp <C-R><C-F> <C-R><C-F>")
vim.keymap.set("n", "\\d", "odebugger<ESC>")
vim.keymap.set("n", "\\d", "odebugger<ESC>")
vim.keymap.set("n", "\\D", "Odebugger<ESC>")
vim.keymap.set("n", "\\da", ":bufdo bd<CR>-")
-- vim.keymap.set('n', '<leader>F',   ':Rg | ')
-- vim.keymap.set("n", "gr", ":Telescope grep_string<CR>")
vim.keymap.set("n", "\\F", ":Telescope live_grep<CR>")
vim.keymap.set("n", "\\g", ":Git ")
vim.keymap.set("n", "\\G", ":Git ")
vim.keymap.set("n", "\\gbl", ":Git blame<CR>")
vim.keymap.set("n", "\\br", ":Git branch<CR>")
vim.keymap.set('n', '\\gbr', ':Git branch<CR>')
vim.keymap.set("n", "\\gbr", ":Telescope git_branches<CR>")
vim.keymap.set("n", "\\gc", ":Git commit<CR>")
vim.keymap.set("n", "\\ch", ":Git checkout | ")
vim.keymap.set("n", "\\fi", "mzgg=G'z")
vim.keymap.set("n", "\\gd", ":Gdiff<CR>")
vim.keymap.set("n", "\\ge", ":Gedit")
vim.keymap.set("n", "\\gf", ":Gfetch")
vim.keymap.set("n", "\\gl", ":Git log<CR>")
vim.keymap.set("n", "\\gm", ":Gmerge | ")
vim.keymap.set("n", "\\gdg", ":diffget")
vim.keymap.set("n", "\\gdp", ":diffput")
vim.keymap.set("n", "\\gp", ":Git push | ")
vim.keymap.set("n", "\\gr", ":Gread")
vim.keymap.set("n", "\\gs", ":Git<CR>")
vim.keymap.set("n", "\\gt", ":Git tree<CR>")
vim.keymap.set("n", "\\gw", ":Gwrite")
vim.keymap.set("n", "\\h", ":tabprev<CR>")
vim.keymap.set("n", "\\js", ":%!python -m json.tool<CR>")
vim.keymap.set("n", "\\l", ":tabnext<CR>")
vim.keymap.set("n", "\\pll", ":Git pull<CR>")
vim.keymap.set("n", "\\psh", ":Git push<CR>")
vim.keymap.set("n", "\\t", ":tabnew<CR>")
vim.keymap.set("n", "\\js", ":%!python -m json.tool<CR>")
vim.keymap.set("n", "\\v", "gg V G")
vim.keymap.set("n", "\\[", ":NeoTreeClose<CR>")
vim.keymap.set("n", "\\]", ":tabnext<CR>")
vim.keymap.set("n", "\\]", ":NeoTreeReveal<CR>")
vim.keymap.set("n", "\\tc", ":tabclose<CR>")
vim.keymap.set("n", ";", ":")
